<?php
/**
 * Amadeco QuickView Module
 *
 * @category   Amadeco
 * @package    Amadeco_QuickView
 * @author     Ilan Parmentier
 */

/** @var \Magento\Catalog\Block\Product\View\Details $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<?php if ($groups = $block->getGroupChildNames('quickview.tabs', 'getChildHtml')): ?>
    <?php $layout = $block->getLayout(); ?>
    <?php if (count($groups) === 1): ?>
        <?php
            $html = $layout->renderElement($groups[0]);
            $alias = $layout->getElementAlias($groups[0]);
        ?>
        <div class="data item content quickview-tab-content"
            id="<?= $escaper->escapeHtmlAttr($alias) ?>">
            <?= /* @noEscape */ $html ?>
        </div>
    <?php else: ?>
        <div class="product data items"
            data-mage-init='{"tabs": {
                "openedState": "active",
                "content": ".quickview-tab-content",
                "header": ".quickview-tab-title",
                "collapsibleElement": ".quickview-tab-title"
            }}'>
            <?php $hideTabContent = false; ?>
            <?php foreach ($groups as $name): ?>
                <?php
                    $html = $layout->renderElement($name);
                    if (!$html || !trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                ?>
                <div id="tab-label-<?= $escaper->escapeHtmlAttr($alias) ?>"
                    class="data item title quickview-tab-title <?= !$hideTabContent ? 'active' : ''?>"
                    aria-labeledby="tab-label-<?= $escaper->escapeHtmlAttr($alias) ?>-title">
                    <a class="data switch"
                        tabindex="-1"
                        data-role="trigger"
                        data-toggle="switch"
                        href="#<?= $escaper->escapeHtmlAttr($alias) ?>"
                        id="tab-label-<?= $escaper->escapeHtmlAttr($alias) ?>-title">
                        <span><?= /* @noEscape */ $label ?></span>
                    </a>
                </div>
                <div class="data item content quickview-tab-content"
                    id="<?= $escaper->escapeHtmlAttr($alias) ?>"
                    aria-labelledby="tab-label-<?= $escaper->escapeHtmlAttr($alias) ?>-title">
                    <?= /* @noEscape */ $html ?>
                </div>
                <?= $hideTabContent
                    ? /* @noEscape */ $secureRenderer->renderStyleAsTag(
                        'display: none;',
                        '#' . $escaper->escapeHtmlAttr($alias)
                    )
                    : '' ?>
                <?php $hideTabContent = true; ?>
            <?php endforeach ?>
        </div>
    <?php endif ?>
<?php endif ?>